services:
  fastapi_test:
    build:
      context: ./fastapi
      dockerfile: Dockerfile.test
    container_name: fastapi_app_test
    working_dir: /app
    volumes:
      - ./fastapi:/app
      - temp_files_volume:/app/src/static/temp
    ports:
      - "8001:8000"
    command: >
      python -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --access-log
    networks:
      - booking
    restart: "no"
    env_file:
      - .test.env
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  temp_files_volume:
    name: temp_files_volume
    external: true

networks:
  booking:
    name: booking
    external: true
