apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booking-images-pvc
  namespace: booking
spec:
  accessModes:
    - ReadWriteMany  # Для возможности монтирования в несколько подов
  resources:
    requests:
      storage: 10Gi  # Размер хранилища для изображений
  # storageClassName: nfs-client  # Раскомментируйте, если используете NFS
  # Если используете стандартный StorageClass, удалите эту строку

